  name : Build & Deploy Spring App

  on:
    push:
      branches:
        - master

  jobs:
    build-deploy:
      name: Build & Deploy Spring App
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
              distribution: 'corretto'
              java-version: '17'
              cache: 'maven'

         - name: Unit Tests
           run: mvn -B test --file pom.xml

         - name: Build the app
           run: |
             mvn clean
             mvn -B package --file pom.xml